export default {
  btw: '/btw',
  clear: '/clear',
  compact: '/compact',
  config: '/config',
  context: '/context',
  exit: '/exit',
  ide: '/ide',
  init: '/init',
  model: '/model',
  permissions: '/permissions',
  plan: '/plan',
  rewind: '/rewind',
  status: '/status',
  statusline: '/statusline',
  usage: '/usage',
}
