export default {
  btw: '/btw',
  clear: '/clear',
  compact: '/compact',
  config: '/config',
  context: '/context',
  doctor: '/doctor',
  exit: '/exit',
  ide: '/ide',
  insights: '/insights',
  init: '/init',
  memory: '/memory',
  model: '/model',
  permissions: '/permissions',
  plan: '/plan',
  powerup: '/powerup',
  rewind: '/rewind',
  status: '/status',
  statusline: '/statusline',
  'terminal-setup': '/terminal-setup',
  ultraplan: '/ultraplan',
  usage: '/usage',
}
